target: ascii atbash base64decode count patch phone testme

ascii: ascii.c
	gcc ascii.c -o ascii
atbash: atbash.c 
	gcc atbash.c -o atbash
base64decode: base64decode.c 
	gcc base64decode.c -o base64decode
count: count.c 
	gcc count.c -o count
patch: patch.c
	gcc patch.c -o patch
phone: phone.c
	gcc phone.c -o phone
testme: testme.c
	gcc testme.c -o testme
clean:
	rm -fv ascii atbash base64decode count patch phone testme a.out
