target: arrays strings memory

arrays: arrays.c
	gcc arrays.c -o arrays
memory: memory.c
	gcc memory.c -o memory
strings: strings.c
	gcc strings.c -o strings
clean: 
	rm -fv arrays strings memory a.out
