target: arrays strings memory hexdump
hexdump: hexdump.c
	gcc hexdump.c -o hexdump
arrays: arrays.c
	gcc arrays.c -o arrays
memory: memory.c
	gcc memory.c -o memory
strings: strings.c
	gcc strings.c -o strings
clean: 
	rm -fv arrays strings memory hexdump a.out
